//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_post
    {
        public club_post()
        {
            this.club_comments = new HashSet<club_postcomment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<System.DateTime> WritingDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ViewsCount { get; set; }
        public string Seo { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual club_category club_category { get; set; }
        public virtual club_member club_member { get; set; }
        public virtual ICollection<club_postcomment> club_comments { get; set; }
        public virtual club_group club_group { get; set; }
    }
}
