//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_category
    {
        public club_category()
        {
            this.club_posts = new HashSet<club_post>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Seo { get; set; }
        public Nullable<int> Sort { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual ICollection<club_post> club_posts { get; set; }
    }
}
