//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class club_member
    {
        public club_member()
        {
            this.club_groups = new HashSet<club_groupmember>();
            this.club_posts = new HashSet<club_post>();
            this.club_comments = new HashSet<club_postcomment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SchoolNo { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
        public string Faculty { get; set; }
        public string Program { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Gender { get; set; }
        public string About { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> Role { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual ICollection<club_groupmember> club_groups { get; set; }
        public virtual ICollection<club_post> club_posts { get; set; }
        public virtual ICollection<club_postcomment> club_comments { get; set; }
    }
}
