//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ItemId { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual user user { get; set; }
    }
}
