//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Mobisis.ObisisServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectModel", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Activity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Document))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Exam))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Lesson))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.ListModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.FoodList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Food))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Graduation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Period))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Program))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Student))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mobisis.ObisisServiceReference.Connection))]
    public partial class ObjectModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Activity", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Activity : Mobisis.ObisisServiceReference.ObjectModel {
        
        private System.DateTime DateField;
        
        private string DescriptionField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Document : Mobisis.ObisisServiceReference.ObjectModel {
        
        private bool IsPrintedField;
        
        private int PrintCountField;
        
        private System.DateTime PrintDateField;
        
        private Mobisis.ObisisServiceReference.ProgramType ProgramField;
        
        private int RequestCountField;
        
        private System.DateTime RequestDateField;
        
        private string TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrinted {
            get {
                return this.IsPrintedField;
            }
            set {
                if ((this.IsPrintedField.Equals(value) != true)) {
                    this.IsPrintedField = value;
                    this.RaisePropertyChanged("IsPrinted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PrintCount {
            get {
                return this.PrintCountField;
            }
            set {
                if ((this.PrintCountField.Equals(value) != true)) {
                    this.PrintCountField = value;
                    this.RaisePropertyChanged("PrintCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PrintDate {
            get {
                return this.PrintDateField;
            }
            set {
                if ((this.PrintDateField.Equals(value) != true)) {
                    this.PrintDateField = value;
                    this.RaisePropertyChanged("PrintDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.ProgramType Program {
            get {
                return this.ProgramField;
            }
            set {
                if ((this.ProgramField.Equals(value) != true)) {
                    this.ProgramField = value;
                    this.RaisePropertyChanged("Program");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RequestCount {
            get {
                return this.RequestCountField;
            }
            set {
                if ((this.RequestCountField.Equals(value) != true)) {
                    this.RequestCountField = value;
                    this.RaisePropertyChanged("RequestCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Exam", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Exam : Mobisis.ObisisServiceReference.ObjectModel {
        
        private System.Nullable<System.DateTime> DateField;
        
        private System.Nullable<int> MarkField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Mark {
            get {
                return this.MarkField;
            }
            set {
                if ((this.MarkField.Equals(value) != true)) {
                    this.MarkField = value;
                    this.RaisePropertyChanged("Mark");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lesson", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Lesson : Mobisis.ObisisServiceReference.ObjectModel {
        
        private System.Nullable<Mobisis.ObisisServiceReference.AbsentType> AbsentStateField;
        
        private System.Nullable<int> AverageField;
        
        private bool AverageEffectField;
        
        private int ClassField;
        
        private string CodeField;
        
        private double CreditField;
        
        private Mobisis.ObisisServiceReference.Exam FinalField;
        
        private Mobisis.ObisisServiceReference.Exam FirstMidtermField;
        
        private System.Nullable<Mobisis.ObisisServiceReference.GradeType> GradeField;
        
        private Mobisis.ObisisServiceReference.Exam IntegrationField;
        
        private System.Nullable<bool> IntegrationRightField;
        
        private string NameField;
        
        private Mobisis.ObisisServiceReference.Exam SecondMidtermField;
        
        private System.Nullable<bool> StateField;
        
        private double SuccessFactorField;
        
        private Mobisis.ObisisServiceReference.Exam ThirdMidtermField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Mobisis.ObisisServiceReference.AbsentType> AbsentState {
            get {
                return this.AbsentStateField;
            }
            set {
                if ((this.AbsentStateField.Equals(value) != true)) {
                    this.AbsentStateField = value;
                    this.RaisePropertyChanged("AbsentState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Average {
            get {
                return this.AverageField;
            }
            set {
                if ((this.AverageField.Equals(value) != true)) {
                    this.AverageField = value;
                    this.RaisePropertyChanged("Average");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AverageEffect {
            get {
                return this.AverageEffectField;
            }
            set {
                if ((this.AverageEffectField.Equals(value) != true)) {
                    this.AverageEffectField = value;
                    this.RaisePropertyChanged("AverageEffect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Class {
            get {
                return this.ClassField;
            }
            set {
                if ((this.ClassField.Equals(value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.Exam Final {
            get {
                return this.FinalField;
            }
            set {
                if ((object.ReferenceEquals(this.FinalField, value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.Exam FirstMidterm {
            get {
                return this.FirstMidtermField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstMidtermField, value) != true)) {
                    this.FirstMidtermField = value;
                    this.RaisePropertyChanged("FirstMidterm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Mobisis.ObisisServiceReference.GradeType> Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.Exam Integration {
            get {
                return this.IntegrationField;
            }
            set {
                if ((object.ReferenceEquals(this.IntegrationField, value) != true)) {
                    this.IntegrationField = value;
                    this.RaisePropertyChanged("Integration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IntegrationRight {
            get {
                return this.IntegrationRightField;
            }
            set {
                if ((this.IntegrationRightField.Equals(value) != true)) {
                    this.IntegrationRightField = value;
                    this.RaisePropertyChanged("IntegrationRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.Exam SecondMidterm {
            get {
                return this.SecondMidtermField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondMidtermField, value) != true)) {
                    this.SecondMidtermField = value;
                    this.RaisePropertyChanged("SecondMidterm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SuccessFactor {
            get {
                return this.SuccessFactorField;
            }
            set {
                if ((this.SuccessFactorField.Equals(value) != true)) {
                    this.SuccessFactorField = value;
                    this.RaisePropertyChanged("SuccessFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.Exam ThirdMidterm {
            get {
                return this.ThirdMidtermField;
            }
            set {
                if ((object.ReferenceEquals(this.ThirdMidtermField, value) != true)) {
                    this.ThirdMidtermField = value;
                    this.RaisePropertyChanged("ThirdMidterm");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListModel", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class ListModel : Mobisis.ObisisServiceReference.ObjectModel {
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.ObjectModel> ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.ObjectModel> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FoodList", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class FoodList : Mobisis.ObisisServiceReference.ObjectModel {
        
        private System.DateTime DateField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Food> FoodsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Food> Foods {
            get {
                return this.FoodsField;
            }
            set {
                if ((object.ReferenceEquals(this.FoodsField, value) != true)) {
                    this.FoodsField = value;
                    this.RaisePropertyChanged("Foods");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Food", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Food : Mobisis.ObisisServiceReference.ObjectModel {
        
        private string CalorieField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calorie {
            get {
                return this.CalorieField;
            }
            set {
                if ((object.ReferenceEquals(this.CalorieField, value) != true)) {
                    this.CalorieField = value;
                    this.RaisePropertyChanged("Calorie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Graduation", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Graduation : Mobisis.ObisisServiceReference.ObjectModel {
        
        private string ConditionField;
        
        private string DescriptionField;
        
        private string StateField;
        
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Period", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Period : Mobisis.ObisisServiceReference.ObjectModel {
        
        private int CodeField;
        
        private double GANOField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Lesson> LessonsField;
        
        private string NameField;
        
        private string YearField;
        
        private int YearCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GANO {
            get {
                return this.GANOField;
            }
            set {
                if ((this.GANOField.Equals(value) != true)) {
                    this.GANOField = value;
                    this.RaisePropertyChanged("GANO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Lesson> Lessons {
            get {
                return this.LessonsField;
            }
            set {
                if ((object.ReferenceEquals(this.LessonsField, value) != true)) {
                    this.LessonsField = value;
                    this.RaisePropertyChanged("Lessons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Year {
            get {
                return this.YearField;
            }
            set {
                if ((object.ReferenceEquals(this.YearField, value) != true)) {
                    this.YearField = value;
                    this.RaisePropertyChanged("Year");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearCode {
            get {
                return this.YearCodeField;
            }
            set {
                if ((this.YearCodeField.Equals(value) != true)) {
                    this.YearCodeField = value;
                    this.RaisePropertyChanged("YearCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Program : Mobisis.ObisisServiceReference.ObjectModel {
        
        private int ClassField;
        
        private string DepartmentField;
        
        private string FacultyField;
        
        private double GANOField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Period> PeriodsField;
        
        private Mobisis.ObisisServiceReference.ProgramType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Class {
            get {
                return this.ClassField;
            }
            set {
                if ((this.ClassField.Equals(value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GANO {
            get {
                return this.GANOField;
            }
            set {
                if ((this.GANOField.Equals(value) != true)) {
                    this.GANOField = value;
                    this.RaisePropertyChanged("GANO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Period> Periods {
            get {
                return this.PeriodsField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodsField, value) != true)) {
                    this.PeriodsField = value;
                    this.RaisePropertyChanged("Periods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.ProgramType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Student : Mobisis.ObisisServiceReference.ObjectModel {
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Document> DocumentsField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Graduation> GraduationStateField;
        
        private int IDField;
        
        private string NameField;
        
        private string PasswordField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Program> ProgramsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Document> Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Graduation> GraduationState {
            get {
                return this.GraduationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.GraduationStateField, value) != true)) {
                    this.GraduationStateField = value;
                    this.RaisePropertyChanged("GraduationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ObisisServiceReference.Program> Programs {
            get {
                return this.ProgramsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramsField, value) != true)) {
                    this.ProgramsField = value;
                    this.RaisePropertyChanged("Programs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Connection", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public partial class Connection : Mobisis.ObisisServiceReference.ObjectModel {
        
        private Mobisis.ObisisServiceReference.ObjectModel DataObjectField;
        
        private string MessageField;
        
        private bool StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ObisisServiceReference.ObjectModel DataObject {
            get {
                return this.DataObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.DataObjectField, value) != true)) {
                    this.DataObjectField = value;
                    this.RaisePropertyChanged("DataObject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProgramType", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public enum ProgramType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Major = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minor = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbsentType", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public enum AbsentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Free = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Passed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = -1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradeType", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Models")]
    public enum GradeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FF = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DD = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DC = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CC = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CB = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BB = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BA = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AA = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ObisisServiceReference.IObisisMobileService")]
    public interface IObisisMobileService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IObisisMobileService/GetStudent", ReplyAction="http://tempuri.org/IObisisMobileService/GetStudentResponse")]
        System.IAsyncResult BeginGetStudent(int studentID, string password, System.AsyncCallback callback, object asyncState);
        
        Mobisis.ObisisServiceReference.Connection EndGetStudent(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IObisisMobileService/GetCurrentPeriod", ReplyAction="http://tempuri.org/IObisisMobileService/GetCurrentPeriodResponse")]
        System.IAsyncResult BeginGetCurrentPeriod(Mobisis.ObisisServiceReference.Period currentPeriod, int studentID, string password, System.AsyncCallback callback, object asyncState);
        
        Mobisis.ObisisServiceReference.Connection EndGetCurrentPeriod(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IObisisMobileService/GetActivities", ReplyAction="http://tempuri.org/IObisisMobileService/GetActivitiesResponse")]
        System.IAsyncResult BeginGetActivities(System.AsyncCallback callback, object asyncState);
        
        Mobisis.ObisisServiceReference.Connection EndGetActivities(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IObisisMobileService/GetFoodLists", ReplyAction="http://tempuri.org/IObisisMobileService/GetFoodListsResponse")]
        System.IAsyncResult BeginGetFoodLists(System.AsyncCallback callback, object asyncState);
        
        Mobisis.ObisisServiceReference.Connection EndGetFoodLists(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObisisMobileServiceChannel : Mobisis.ObisisServiceReference.IObisisMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStudentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStudentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mobisis.ObisisServiceReference.Connection Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mobisis.ObisisServiceReference.Connection)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCurrentPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCurrentPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mobisis.ObisisServiceReference.Connection Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mobisis.ObisisServiceReference.Connection)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetActivitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetActivitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mobisis.ObisisServiceReference.Connection Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mobisis.ObisisServiceReference.Connection)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFoodListsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFoodListsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mobisis.ObisisServiceReference.Connection Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mobisis.ObisisServiceReference.Connection)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObisisMobileServiceClient : System.ServiceModel.ClientBase<Mobisis.ObisisServiceReference.IObisisMobileService>, Mobisis.ObisisServiceReference.IObisisMobileService {
        
        private BeginOperationDelegate onBeginGetStudentDelegate;
        
        private EndOperationDelegate onEndGetStudentDelegate;
        
        private System.Threading.SendOrPostCallback onGetStudentCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCurrentPeriodDelegate;
        
        private EndOperationDelegate onEndGetCurrentPeriodDelegate;
        
        private System.Threading.SendOrPostCallback onGetCurrentPeriodCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetActivitiesDelegate;
        
        private EndOperationDelegate onEndGetActivitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetActivitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFoodListsDelegate;
        
        private EndOperationDelegate onEndGetFoodListsDelegate;
        
        private System.Threading.SendOrPostCallback onGetFoodListsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ObisisMobileServiceClient() {
        }
        
        public ObisisMobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObisisMobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObisisMobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObisisMobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetStudentCompletedEventArgs> GetStudentCompleted;
        
        public event System.EventHandler<GetCurrentPeriodCompletedEventArgs> GetCurrentPeriodCompleted;
        
        public event System.EventHandler<GetActivitiesCompletedEventArgs> GetActivitiesCompleted;
        
        public event System.EventHandler<GetFoodListsCompletedEventArgs> GetFoodListsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ObisisServiceReference.IObisisMobileService.BeginGetStudent(int studentID, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStudent(studentID, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobisis.ObisisServiceReference.Connection Mobisis.ObisisServiceReference.IObisisMobileService.EndGetStudent(System.IAsyncResult result) {
            return base.Channel.EndGetStudent(result);
        }
        
        private System.IAsyncResult OnBeginGetStudent(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int studentID = ((int)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).BeginGetStudent(studentID, password, callback, asyncState);
        }
        
        private object[] OnEndGetStudent(System.IAsyncResult result) {
            Mobisis.ObisisServiceReference.Connection retVal = ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).EndGetStudent(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStudentCompleted(object state) {
            if ((this.GetStudentCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStudentCompleted(this, new GetStudentCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStudentAsync(int studentID, string password) {
            this.GetStudentAsync(studentID, password, null);
        }
        
        public void GetStudentAsync(int studentID, string password, object userState) {
            if ((this.onBeginGetStudentDelegate == null)) {
                this.onBeginGetStudentDelegate = new BeginOperationDelegate(this.OnBeginGetStudent);
            }
            if ((this.onEndGetStudentDelegate == null)) {
                this.onEndGetStudentDelegate = new EndOperationDelegate(this.OnEndGetStudent);
            }
            if ((this.onGetStudentCompletedDelegate == null)) {
                this.onGetStudentCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStudentCompleted);
            }
            base.InvokeAsync(this.onBeginGetStudentDelegate, new object[] {
                        studentID,
                        password}, this.onEndGetStudentDelegate, this.onGetStudentCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ObisisServiceReference.IObisisMobileService.BeginGetCurrentPeriod(Mobisis.ObisisServiceReference.Period currentPeriod, int studentID, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCurrentPeriod(currentPeriod, studentID, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobisis.ObisisServiceReference.Connection Mobisis.ObisisServiceReference.IObisisMobileService.EndGetCurrentPeriod(System.IAsyncResult result) {
            return base.Channel.EndGetCurrentPeriod(result);
        }
        
        private System.IAsyncResult OnBeginGetCurrentPeriod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Mobisis.ObisisServiceReference.Period currentPeriod = ((Mobisis.ObisisServiceReference.Period)(inValues[0]));
            int studentID = ((int)(inValues[1]));
            string password = ((string)(inValues[2]));
            return ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).BeginGetCurrentPeriod(currentPeriod, studentID, password, callback, asyncState);
        }
        
        private object[] OnEndGetCurrentPeriod(System.IAsyncResult result) {
            Mobisis.ObisisServiceReference.Connection retVal = ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).EndGetCurrentPeriod(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCurrentPeriodCompleted(object state) {
            if ((this.GetCurrentPeriodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCurrentPeriodCompleted(this, new GetCurrentPeriodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCurrentPeriodAsync(Mobisis.ObisisServiceReference.Period currentPeriod, int studentID, string password) {
            this.GetCurrentPeriodAsync(currentPeriod, studentID, password, null);
        }
        
        public void GetCurrentPeriodAsync(Mobisis.ObisisServiceReference.Period currentPeriod, int studentID, string password, object userState) {
            if ((this.onBeginGetCurrentPeriodDelegate == null)) {
                this.onBeginGetCurrentPeriodDelegate = new BeginOperationDelegate(this.OnBeginGetCurrentPeriod);
            }
            if ((this.onEndGetCurrentPeriodDelegate == null)) {
                this.onEndGetCurrentPeriodDelegate = new EndOperationDelegate(this.OnEndGetCurrentPeriod);
            }
            if ((this.onGetCurrentPeriodCompletedDelegate == null)) {
                this.onGetCurrentPeriodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCurrentPeriodCompleted);
            }
            base.InvokeAsync(this.onBeginGetCurrentPeriodDelegate, new object[] {
                        currentPeriod,
                        studentID,
                        password}, this.onEndGetCurrentPeriodDelegate, this.onGetCurrentPeriodCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ObisisServiceReference.IObisisMobileService.BeginGetActivities(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetActivities(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobisis.ObisisServiceReference.Connection Mobisis.ObisisServiceReference.IObisisMobileService.EndGetActivities(System.IAsyncResult result) {
            return base.Channel.EndGetActivities(result);
        }
        
        private System.IAsyncResult OnBeginGetActivities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).BeginGetActivities(callback, asyncState);
        }
        
        private object[] OnEndGetActivities(System.IAsyncResult result) {
            Mobisis.ObisisServiceReference.Connection retVal = ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).EndGetActivities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetActivitiesCompleted(object state) {
            if ((this.GetActivitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetActivitiesCompleted(this, new GetActivitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetActivitiesAsync() {
            this.GetActivitiesAsync(null);
        }
        
        public void GetActivitiesAsync(object userState) {
            if ((this.onBeginGetActivitiesDelegate == null)) {
                this.onBeginGetActivitiesDelegate = new BeginOperationDelegate(this.OnBeginGetActivities);
            }
            if ((this.onEndGetActivitiesDelegate == null)) {
                this.onEndGetActivitiesDelegate = new EndOperationDelegate(this.OnEndGetActivities);
            }
            if ((this.onGetActivitiesCompletedDelegate == null)) {
                this.onGetActivitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetActivitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetActivitiesDelegate, null, this.onEndGetActivitiesDelegate, this.onGetActivitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ObisisServiceReference.IObisisMobileService.BeginGetFoodLists(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFoodLists(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobisis.ObisisServiceReference.Connection Mobisis.ObisisServiceReference.IObisisMobileService.EndGetFoodLists(System.IAsyncResult result) {
            return base.Channel.EndGetFoodLists(result);
        }
        
        private System.IAsyncResult OnBeginGetFoodLists(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).BeginGetFoodLists(callback, asyncState);
        }
        
        private object[] OnEndGetFoodLists(System.IAsyncResult result) {
            Mobisis.ObisisServiceReference.Connection retVal = ((Mobisis.ObisisServiceReference.IObisisMobileService)(this)).EndGetFoodLists(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFoodListsCompleted(object state) {
            if ((this.GetFoodListsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFoodListsCompleted(this, new GetFoodListsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFoodListsAsync() {
            this.GetFoodListsAsync(null);
        }
        
        public void GetFoodListsAsync(object userState) {
            if ((this.onBeginGetFoodListsDelegate == null)) {
                this.onBeginGetFoodListsDelegate = new BeginOperationDelegate(this.OnBeginGetFoodLists);
            }
            if ((this.onEndGetFoodListsDelegate == null)) {
                this.onEndGetFoodListsDelegate = new EndOperationDelegate(this.OnEndGetFoodLists);
            }
            if ((this.onGetFoodListsCompletedDelegate == null)) {
                this.onGetFoodListsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFoodListsCompleted);
            }
            base.InvokeAsync(this.onBeginGetFoodListsDelegate, null, this.onEndGetFoodListsDelegate, this.onGetFoodListsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Mobisis.ObisisServiceReference.IObisisMobileService CreateChannel() {
            return new ObisisMobileServiceClientChannel(this);
        }
        
        private class ObisisMobileServiceClientChannel : ChannelBase<Mobisis.ObisisServiceReference.IObisisMobileService>, Mobisis.ObisisServiceReference.IObisisMobileService {
            
            public ObisisMobileServiceClientChannel(System.ServiceModel.ClientBase<Mobisis.ObisisServiceReference.IObisisMobileService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetStudent(int studentID, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = studentID;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("GetStudent", _args, callback, asyncState);
                return _result;
            }
            
            public Mobisis.ObisisServiceReference.Connection EndGetStudent(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mobisis.ObisisServiceReference.Connection _result = ((Mobisis.ObisisServiceReference.Connection)(base.EndInvoke("GetStudent", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetCurrentPeriod(Mobisis.ObisisServiceReference.Period currentPeriod, int studentID, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = currentPeriod;
                _args[1] = studentID;
                _args[2] = password;
                System.IAsyncResult _result = base.BeginInvoke("GetCurrentPeriod", _args, callback, asyncState);
                return _result;
            }
            
            public Mobisis.ObisisServiceReference.Connection EndGetCurrentPeriod(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mobisis.ObisisServiceReference.Connection _result = ((Mobisis.ObisisServiceReference.Connection)(base.EndInvoke("GetCurrentPeriod", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetActivities(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetActivities", _args, callback, asyncState);
                return _result;
            }
            
            public Mobisis.ObisisServiceReference.Connection EndGetActivities(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mobisis.ObisisServiceReference.Connection _result = ((Mobisis.ObisisServiceReference.Connection)(base.EndInvoke("GetActivities", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFoodLists(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetFoodLists", _args, callback, asyncState);
                return _result;
            }
            
            public Mobisis.ObisisServiceReference.Connection EndGetFoodLists(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mobisis.ObisisServiceReference.Connection _result = ((Mobisis.ObisisServiceReference.Connection)(base.EndInvoke("GetFoodLists", _args, result)));
                return _result;
            }
        }
    }
}
