//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.Transport.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JourneyStop
    {
        public int Id { get; set; }
        public int JourneyId { get; set; }
        public int PlaceId { get; set; }
        public System.DateTime EstimatedDate { get; set; }
        public int Sort { get; set; }
        public int PassengerCountGetOff { get; set; }
        public int PassengerCountGetOn { get; set; }
    
        public virtual Journey Journey { get; set; }
        public virtual Place Place { get; set; }
    }
}
