//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.Transport.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationAction
    {
        public int Id { get; set; }
        public int ReservationId { get; set; }
        public int Type { get; set; }
        public int EditedMemberId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
