//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.Transport.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transporter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transporter()
        {
            this.Journeys = new HashSet<Journey>();
        }
    
        public int Id { get; set; }
        public string Plate { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public string SeatSchema { get; set; }
        public int DriverId { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public int WorkingCityId { get; set; }
        public int DepartureDistance { get; set; }
        public int ArrivalDistance { get; set; }
        public string WorkingHours { get; set; }
        public bool IsActivatedUpstate { get; set; }
        public int Type { get; set; }
        public int MinimumDistance { get; set; }
        public int MaximumDistance { get; set; }
        public double PricePerKilometer { get; set; }
        public int PassengerCount { get; set; }
        public Nullable<int> TotalBaggageCapacity { get; set; }
    
        public virtual Factory Factory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Journey> Journeys { get; set; }
        public virtual Member Member { get; set; }
        public virtual Place Place { get; set; }
    }
}
