//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace AppSupport.SupportService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Support", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Data")]
    public partial class Support : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AppSupport.SupportService.App AppField;
        
        private int AppIdField;
        
        private AppSupport.SupportService.Consumer ConsumerField;
        
        private int ConsumerIdField;
        
        private string ContentField;
        
        private int IdField;
        
        private bool IsFlaggedField;
        
        private bool IsReadField;
        
        private System.DateTime SendDateField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppSupport.SupportService.App App {
            get {
                return this.AppField;
            }
            set {
                if ((object.ReferenceEquals(this.AppField, value) != true)) {
                    this.AppField = value;
                    this.RaisePropertyChanged("App");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((this.AppIdField.Equals(value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppSupport.SupportService.Consumer Consumer {
            get {
                return this.ConsumerField;
            }
            set {
                if ((object.ReferenceEquals(this.ConsumerField, value) != true)) {
                    this.ConsumerField = value;
                    this.RaisePropertyChanged("Consumer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConsumerId {
            get {
                return this.ConsumerIdField;
            }
            set {
                if ((this.ConsumerIdField.Equals(value) != true)) {
                    this.ConsumerIdField = value;
                    this.RaisePropertyChanged("ConsumerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFlagged {
            get {
                return this.IsFlaggedField;
            }
            set {
                if ((this.IsFlaggedField.Equals(value) != true)) {
                    this.IsFlaggedField = value;
                    this.RaisePropertyChanged("IsFlagged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsRead {
            get {
                return this.IsReadField;
            }
            set {
                if ((this.IsReadField.Equals(value) != true)) {
                    this.IsReadField = value;
                    this.RaisePropertyChanged("IsRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="App", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Data")]
    public partial class App : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string NameField;
        
        private string PlatformField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform {
            get {
                return this.PlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                    this.PlatformField = value;
                    this.RaisePropertyChanged("Platform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Consumer", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Data")]
    public partial class Consumer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string EmailField;
        
        private int IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Admin", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Data")]
    public partial class Admin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupportList", Namespace="http://schemas.datacontract.org/2004/07/ObisisService.Data")]
    public partial class SupportList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<AppSupport.SupportService.Support> ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<AppSupport.SupportService.Support> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SupportService.IConsumerSupportService")]
    public interface IConsumerSupportService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsumerSupportService/CreateSupport", ReplyAction="http://tempuri.org/IConsumerSupportService/CreateSupportResponse")]
        System.IAsyncResult BeginCreateSupport(AppSupport.SupportService.Support support, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateSupport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsumerSupportService/ListSupports", ReplyAction="http://tempuri.org/IConsumerSupportService/ListSupportsResponse")]
        System.IAsyncResult BeginListSupports(AppSupport.SupportService.Admin admin, System.AsyncCallback callback, object asyncState);
        
        AppSupport.SupportService.SupportList EndListSupports(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsumerSupportService/ViewSupport", ReplyAction="http://tempuri.org/IConsumerSupportService/ViewSupportResponse")]
        System.IAsyncResult BeginViewSupport(AppSupport.SupportService.Admin admin, int id, System.AsyncCallback callback, object asyncState);
        
        AppSupport.SupportService.Support EndViewSupport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsumerSupportService/UpdateFlagSupport", ReplyAction="http://tempuri.org/IConsumerSupportService/UpdateFlagSupportResponse")]
        System.IAsyncResult BeginUpdateFlagSupport(AppSupport.SupportService.Admin admin, int id, bool state, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdateFlagSupport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsumerSupportService/ReplySupport", ReplyAction="http://tempuri.org/IConsumerSupportService/ReplySupportResponse")]
        System.IAsyncResult BeginReplySupport(AppSupport.SupportService.Admin admin, AppSupport.SupportService.Consumer consumer, string text, System.AsyncCallback callback, object asyncState);
        
        bool EndReplySupport(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IConsumerSupportService/DeleteSupport", ReplyAction="http://tempuri.org/IConsumerSupportService/DeleteSupportResponse")]
        System.IAsyncResult BeginDeleteSupport(AppSupport.SupportService.Admin admin, int id, System.AsyncCallback callback, object asyncState);
        
        bool EndDeleteSupport(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConsumerSupportServiceChannel : AppSupport.SupportService.IConsumerSupportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateSupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateSupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListSupportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListSupportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppSupport.SupportService.SupportList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppSupport.SupportService.SupportList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ViewSupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ViewSupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppSupport.SupportService.Support Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppSupport.SupportService.Support)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateFlagSupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateFlagSupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReplySupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ReplySupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteSupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteSupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsumerSupportServiceClient : System.ServiceModel.ClientBase<AppSupport.SupportService.IConsumerSupportService>, AppSupport.SupportService.IConsumerSupportService {
        
        private BeginOperationDelegate onBeginCreateSupportDelegate;
        
        private EndOperationDelegate onEndCreateSupportDelegate;
        
        private System.Threading.SendOrPostCallback onCreateSupportCompletedDelegate;
        
        private BeginOperationDelegate onBeginListSupportsDelegate;
        
        private EndOperationDelegate onEndListSupportsDelegate;
        
        private System.Threading.SendOrPostCallback onListSupportsCompletedDelegate;
        
        private BeginOperationDelegate onBeginViewSupportDelegate;
        
        private EndOperationDelegate onEndViewSupportDelegate;
        
        private System.Threading.SendOrPostCallback onViewSupportCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateFlagSupportDelegate;
        
        private EndOperationDelegate onEndUpdateFlagSupportDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateFlagSupportCompletedDelegate;
        
        private BeginOperationDelegate onBeginReplySupportDelegate;
        
        private EndOperationDelegate onEndReplySupportDelegate;
        
        private System.Threading.SendOrPostCallback onReplySupportCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteSupportDelegate;
        
        private EndOperationDelegate onEndDeleteSupportDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteSupportCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ConsumerSupportServiceClient() {
        }
        
        public ConsumerSupportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsumerSupportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumerSupportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsumerSupportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<CreateSupportCompletedEventArgs> CreateSupportCompleted;
        
        public event System.EventHandler<ListSupportsCompletedEventArgs> ListSupportsCompleted;
        
        public event System.EventHandler<ViewSupportCompletedEventArgs> ViewSupportCompleted;
        
        public event System.EventHandler<UpdateFlagSupportCompletedEventArgs> UpdateFlagSupportCompleted;
        
        public event System.EventHandler<ReplySupportCompletedEventArgs> ReplySupportCompleted;
        
        public event System.EventHandler<DeleteSupportCompletedEventArgs> DeleteSupportCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppSupport.SupportService.IConsumerSupportService.BeginCreateSupport(AppSupport.SupportService.Support support, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateSupport(support, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppSupport.SupportService.IConsumerSupportService.EndCreateSupport(System.IAsyncResult result) {
            return base.Channel.EndCreateSupport(result);
        }
        
        private System.IAsyncResult OnBeginCreateSupport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppSupport.SupportService.Support support = ((AppSupport.SupportService.Support)(inValues[0]));
            return ((AppSupport.SupportService.IConsumerSupportService)(this)).BeginCreateSupport(support, callback, asyncState);
        }
        
        private object[] OnEndCreateSupport(System.IAsyncResult result) {
            bool retVal = ((AppSupport.SupportService.IConsumerSupportService)(this)).EndCreateSupport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateSupportCompleted(object state) {
            if ((this.CreateSupportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateSupportCompleted(this, new CreateSupportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateSupportAsync(AppSupport.SupportService.Support support) {
            this.CreateSupportAsync(support, null);
        }
        
        public void CreateSupportAsync(AppSupport.SupportService.Support support, object userState) {
            if ((this.onBeginCreateSupportDelegate == null)) {
                this.onBeginCreateSupportDelegate = new BeginOperationDelegate(this.OnBeginCreateSupport);
            }
            if ((this.onEndCreateSupportDelegate == null)) {
                this.onEndCreateSupportDelegate = new EndOperationDelegate(this.OnEndCreateSupport);
            }
            if ((this.onCreateSupportCompletedDelegate == null)) {
                this.onCreateSupportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateSupportCompleted);
            }
            base.InvokeAsync(this.onBeginCreateSupportDelegate, new object[] {
                        support}, this.onEndCreateSupportDelegate, this.onCreateSupportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppSupport.SupportService.IConsumerSupportService.BeginListSupports(AppSupport.SupportService.Admin admin, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListSupports(admin, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppSupport.SupportService.SupportList AppSupport.SupportService.IConsumerSupportService.EndListSupports(System.IAsyncResult result) {
            return base.Channel.EndListSupports(result);
        }
        
        private System.IAsyncResult OnBeginListSupports(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppSupport.SupportService.Admin admin = ((AppSupport.SupportService.Admin)(inValues[0]));
            return ((AppSupport.SupportService.IConsumerSupportService)(this)).BeginListSupports(admin, callback, asyncState);
        }
        
        private object[] OnEndListSupports(System.IAsyncResult result) {
            AppSupport.SupportService.SupportList retVal = ((AppSupport.SupportService.IConsumerSupportService)(this)).EndListSupports(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListSupportsCompleted(object state) {
            if ((this.ListSupportsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListSupportsCompleted(this, new ListSupportsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListSupportsAsync(AppSupport.SupportService.Admin admin) {
            this.ListSupportsAsync(admin, null);
        }
        
        public void ListSupportsAsync(AppSupport.SupportService.Admin admin, object userState) {
            if ((this.onBeginListSupportsDelegate == null)) {
                this.onBeginListSupportsDelegate = new BeginOperationDelegate(this.OnBeginListSupports);
            }
            if ((this.onEndListSupportsDelegate == null)) {
                this.onEndListSupportsDelegate = new EndOperationDelegate(this.OnEndListSupports);
            }
            if ((this.onListSupportsCompletedDelegate == null)) {
                this.onListSupportsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListSupportsCompleted);
            }
            base.InvokeAsync(this.onBeginListSupportsDelegate, new object[] {
                        admin}, this.onEndListSupportsDelegate, this.onListSupportsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppSupport.SupportService.IConsumerSupportService.BeginViewSupport(AppSupport.SupportService.Admin admin, int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginViewSupport(admin, id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppSupport.SupportService.Support AppSupport.SupportService.IConsumerSupportService.EndViewSupport(System.IAsyncResult result) {
            return base.Channel.EndViewSupport(result);
        }
        
        private System.IAsyncResult OnBeginViewSupport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppSupport.SupportService.Admin admin = ((AppSupport.SupportService.Admin)(inValues[0]));
            int id = ((int)(inValues[1]));
            return ((AppSupport.SupportService.IConsumerSupportService)(this)).BeginViewSupport(admin, id, callback, asyncState);
        }
        
        private object[] OnEndViewSupport(System.IAsyncResult result) {
            AppSupport.SupportService.Support retVal = ((AppSupport.SupportService.IConsumerSupportService)(this)).EndViewSupport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnViewSupportCompleted(object state) {
            if ((this.ViewSupportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ViewSupportCompleted(this, new ViewSupportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ViewSupportAsync(AppSupport.SupportService.Admin admin, int id) {
            this.ViewSupportAsync(admin, id, null);
        }
        
        public void ViewSupportAsync(AppSupport.SupportService.Admin admin, int id, object userState) {
            if ((this.onBeginViewSupportDelegate == null)) {
                this.onBeginViewSupportDelegate = new BeginOperationDelegate(this.OnBeginViewSupport);
            }
            if ((this.onEndViewSupportDelegate == null)) {
                this.onEndViewSupportDelegate = new EndOperationDelegate(this.OnEndViewSupport);
            }
            if ((this.onViewSupportCompletedDelegate == null)) {
                this.onViewSupportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnViewSupportCompleted);
            }
            base.InvokeAsync(this.onBeginViewSupportDelegate, new object[] {
                        admin,
                        id}, this.onEndViewSupportDelegate, this.onViewSupportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppSupport.SupportService.IConsumerSupportService.BeginUpdateFlagSupport(AppSupport.SupportService.Admin admin, int id, bool state, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateFlagSupport(admin, id, state, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppSupport.SupportService.IConsumerSupportService.EndUpdateFlagSupport(System.IAsyncResult result) {
            return base.Channel.EndUpdateFlagSupport(result);
        }
        
        private System.IAsyncResult OnBeginUpdateFlagSupport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppSupport.SupportService.Admin admin = ((AppSupport.SupportService.Admin)(inValues[0]));
            int id = ((int)(inValues[1]));
            bool state = ((bool)(inValues[2]));
            return ((AppSupport.SupportService.IConsumerSupportService)(this)).BeginUpdateFlagSupport(admin, id, state, callback, asyncState);
        }
        
        private object[] OnEndUpdateFlagSupport(System.IAsyncResult result) {
            bool retVal = ((AppSupport.SupportService.IConsumerSupportService)(this)).EndUpdateFlagSupport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateFlagSupportCompleted(object state) {
            if ((this.UpdateFlagSupportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateFlagSupportCompleted(this, new UpdateFlagSupportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateFlagSupportAsync(AppSupport.SupportService.Admin admin, int id, bool state) {
            this.UpdateFlagSupportAsync(admin, id, state, null);
        }
        
        public void UpdateFlagSupportAsync(AppSupport.SupportService.Admin admin, int id, bool state, object userState) {
            if ((this.onBeginUpdateFlagSupportDelegate == null)) {
                this.onBeginUpdateFlagSupportDelegate = new BeginOperationDelegate(this.OnBeginUpdateFlagSupport);
            }
            if ((this.onEndUpdateFlagSupportDelegate == null)) {
                this.onEndUpdateFlagSupportDelegate = new EndOperationDelegate(this.OnEndUpdateFlagSupport);
            }
            if ((this.onUpdateFlagSupportCompletedDelegate == null)) {
                this.onUpdateFlagSupportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateFlagSupportCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateFlagSupportDelegate, new object[] {
                        admin,
                        id,
                        state}, this.onEndUpdateFlagSupportDelegate, this.onUpdateFlagSupportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppSupport.SupportService.IConsumerSupportService.BeginReplySupport(AppSupport.SupportService.Admin admin, AppSupport.SupportService.Consumer consumer, string text, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginReplySupport(admin, consumer, text, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppSupport.SupportService.IConsumerSupportService.EndReplySupport(System.IAsyncResult result) {
            return base.Channel.EndReplySupport(result);
        }
        
        private System.IAsyncResult OnBeginReplySupport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppSupport.SupportService.Admin admin = ((AppSupport.SupportService.Admin)(inValues[0]));
            AppSupport.SupportService.Consumer consumer = ((AppSupport.SupportService.Consumer)(inValues[1]));
            string text = ((string)(inValues[2]));
            return ((AppSupport.SupportService.IConsumerSupportService)(this)).BeginReplySupport(admin, consumer, text, callback, asyncState);
        }
        
        private object[] OnEndReplySupport(System.IAsyncResult result) {
            bool retVal = ((AppSupport.SupportService.IConsumerSupportService)(this)).EndReplySupport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnReplySupportCompleted(object state) {
            if ((this.ReplySupportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ReplySupportCompleted(this, new ReplySupportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ReplySupportAsync(AppSupport.SupportService.Admin admin, AppSupport.SupportService.Consumer consumer, string text) {
            this.ReplySupportAsync(admin, consumer, text, null);
        }
        
        public void ReplySupportAsync(AppSupport.SupportService.Admin admin, AppSupport.SupportService.Consumer consumer, string text, object userState) {
            if ((this.onBeginReplySupportDelegate == null)) {
                this.onBeginReplySupportDelegate = new BeginOperationDelegate(this.OnBeginReplySupport);
            }
            if ((this.onEndReplySupportDelegate == null)) {
                this.onEndReplySupportDelegate = new EndOperationDelegate(this.OnEndReplySupport);
            }
            if ((this.onReplySupportCompletedDelegate == null)) {
                this.onReplySupportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnReplySupportCompleted);
            }
            base.InvokeAsync(this.onBeginReplySupportDelegate, new object[] {
                        admin,
                        consumer,
                        text}, this.onEndReplySupportDelegate, this.onReplySupportCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppSupport.SupportService.IConsumerSupportService.BeginDeleteSupport(AppSupport.SupportService.Admin admin, int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteSupport(admin, id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppSupport.SupportService.IConsumerSupportService.EndDeleteSupport(System.IAsyncResult result) {
            return base.Channel.EndDeleteSupport(result);
        }
        
        private System.IAsyncResult OnBeginDeleteSupport(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppSupport.SupportService.Admin admin = ((AppSupport.SupportService.Admin)(inValues[0]));
            int id = ((int)(inValues[1]));
            return ((AppSupport.SupportService.IConsumerSupportService)(this)).BeginDeleteSupport(admin, id, callback, asyncState);
        }
        
        private object[] OnEndDeleteSupport(System.IAsyncResult result) {
            bool retVal = ((AppSupport.SupportService.IConsumerSupportService)(this)).EndDeleteSupport(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteSupportCompleted(object state) {
            if ((this.DeleteSupportCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteSupportCompleted(this, new DeleteSupportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteSupportAsync(AppSupport.SupportService.Admin admin, int id) {
            this.DeleteSupportAsync(admin, id, null);
        }
        
        public void DeleteSupportAsync(AppSupport.SupportService.Admin admin, int id, object userState) {
            if ((this.onBeginDeleteSupportDelegate == null)) {
                this.onBeginDeleteSupportDelegate = new BeginOperationDelegate(this.OnBeginDeleteSupport);
            }
            if ((this.onEndDeleteSupportDelegate == null)) {
                this.onEndDeleteSupportDelegate = new EndOperationDelegate(this.OnEndDeleteSupport);
            }
            if ((this.onDeleteSupportCompletedDelegate == null)) {
                this.onDeleteSupportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteSupportCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteSupportDelegate, new object[] {
                        admin,
                        id}, this.onEndDeleteSupportDelegate, this.onDeleteSupportCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AppSupport.SupportService.IConsumerSupportService CreateChannel() {
            return new ConsumerSupportServiceClientChannel(this);
        }
        
        private class ConsumerSupportServiceClientChannel : ChannelBase<AppSupport.SupportService.IConsumerSupportService>, AppSupport.SupportService.IConsumerSupportService {
            
            public ConsumerSupportServiceClientChannel(System.ServiceModel.ClientBase<AppSupport.SupportService.IConsumerSupportService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCreateSupport(AppSupport.SupportService.Support support, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = support;
                System.IAsyncResult _result = base.BeginInvoke("CreateSupport", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateSupport(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateSupport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListSupports(AppSupport.SupportService.Admin admin, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = admin;
                System.IAsyncResult _result = base.BeginInvoke("ListSupports", _args, callback, asyncState);
                return _result;
            }
            
            public AppSupport.SupportService.SupportList EndListSupports(System.IAsyncResult result) {
                object[] _args = new object[0];
                AppSupport.SupportService.SupportList _result = ((AppSupport.SupportService.SupportList)(base.EndInvoke("ListSupports", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginViewSupport(AppSupport.SupportService.Admin admin, int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = admin;
                _args[1] = id;
                System.IAsyncResult _result = base.BeginInvoke("ViewSupport", _args, callback, asyncState);
                return _result;
            }
            
            public AppSupport.SupportService.Support EndViewSupport(System.IAsyncResult result) {
                object[] _args = new object[0];
                AppSupport.SupportService.Support _result = ((AppSupport.SupportService.Support)(base.EndInvoke("ViewSupport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateFlagSupport(AppSupport.SupportService.Admin admin, int id, bool state, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = admin;
                _args[1] = id;
                _args[2] = state;
                System.IAsyncResult _result = base.BeginInvoke("UpdateFlagSupport", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndUpdateFlagSupport(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("UpdateFlagSupport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginReplySupport(AppSupport.SupportService.Admin admin, AppSupport.SupportService.Consumer consumer, string text, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = admin;
                _args[1] = consumer;
                _args[2] = text;
                System.IAsyncResult _result = base.BeginInvoke("ReplySupport", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndReplySupport(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("ReplySupport", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteSupport(AppSupport.SupportService.Admin admin, int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = admin;
                _args[1] = id;
                System.IAsyncResult _result = base.BeginInvoke("DeleteSupport", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndDeleteSupport(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("DeleteSupport", _args, result)));
                return _result;
            }
        }
    }
}
