//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_etkinlik
    {
        public bgk_etkinlik()
        {
            this.bgk_butce = new HashSet<bgk_butce>();
            this.bgk_etkinlik_gorevli = new HashSet<bgk_etkinlik_gorevli>();
            this.bgk_etkinlik_konusmaci = new HashSet<bgk_etkinlik_konusmaci>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> FirmaID { get; set; }
        public Nullable<int> AfisID { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
    
        public virtual ICollection<bgk_butce> bgk_butce { get; set; }
        public virtual bgk_dosya bgk_dosya { get; set; }
        public virtual bgk_firma bgk_firma { get; set; }
        public virtual ICollection<bgk_etkinlik_gorevli> bgk_etkinlik_gorevli { get; set; }
        public virtual ICollection<bgk_etkinlik_konusmaci> bgk_etkinlik_konusmaci { get; set; }
    }
}
