//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_galeri_resim
    {
        public int Id { get; set; }
        public string Aciklama { get; set; }
        public int ResimID { get; set; }
        public int GaleriID { get; set; }
        public int Sira { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public bool Onay { get; set; }
    
        public virtual bgk_dosya bgk_dosya { get; set; }
        public virtual bgk_galeri bgk_galeri { get; set; }
    }
}
