//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_mesaj
    {
        public int Id { get; set; }
        public string Mesaj { get; set; }
        public int Tip { get; set; }
        public int GonderenID { get; set; }
        public int AliciID { get; set; }
        public bool Okundu { get; set; }
        public System.DateTime YazimTarihi { get; set; }
    }
}
