//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_yetki
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public bool Yazi { get; set; }
        public bool Yorum { get; set; }
        public bool Sayfa { get; set; }
        public bool Ayar { get; set; }
        public bool Etkinlik { get; set; }
        public bool Butce { get; set; }
        public bool Dosya { get; set; }
        public bool Grup { get; set; }
        public bool Gorev { get; set; }
        public bool Bildirim { get; set; }
        public bool Firma { get; set; }
        public bool Link { get; set; }
        public bool Uye { get; set; }
        public bool Seviye { get; set; }
        public bool Dokuman { get; set; }
        public bool Not { get; set; }
        public bool Galeri { get; set; }
        public bool Anket { get; set; }
        public bool YaziOnay { get; set; }
        public bool YorumOnay { get; set; }
        public bool GorevVerme { get; set; }
        public Nullable<int> Kod { get; set; }
        public bool YaziYazma { get; set; }
        public bool YorumYazma { get; set; }
        public bool BakimdaGiris { get; set; }
        public bool OyKullanma { get; set; }
    }
}
