//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_anket_secim
    {
        public int Id { get; set; }
        public Nullable<int> UyeID { get; set; }
        public int SecenekID { get; set; }
        public string OylayanIP { get; set; }
        public System.DateTime SecimTarihi { get; set; }
    
        public virtual bgk_anket_secenek bgk_anket_secenek { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
    }
}
