//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_dokuman
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Icerik { get; set; }
        public int UyeID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public bool Onay { get; set; }
        public string Seo { get; set; }
        public int Sira { get; set; }
        public int KategoriID { get; set; }
        public Nullable<int> DosyaID { get; set; }
    
        public virtual bgk_dosya bgk_dosya { get; set; }
        public virtual bgk_dokuman_kategori bgk_dokuman_kategori { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
    }
}
