//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_gorev_uye
    {
        public int Id { get; set; }
        public string Aciklama { get; set; }
        public int UyeID { get; set; }
        public int GorevID { get; set; }
        public string Rapor { get; set; }
        public Nullable<int> DosyaID { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public bool Tamamlandi { get; set; }
        public Nullable<bool> Kabul { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual bgk_dosya bgk_dosya { get; set; }
        public virtual bgk_gorev bgk_gorev { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
    }
}
