//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BGKEntities : DbContext
    {
        public BGKEntities()
            : base("name=BGKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bgk_yetki> bgk_yetki { get; set; }
        public DbSet<bgk_anket> bgk_anket { get; set; }
        public DbSet<bgk_anket_secenek> bgk_anket_secenek { get; set; }
        public DbSet<bgk_anket_secim> bgk_anket_secim { get; set; }
        public DbSet<bgk_ayar> bgk_ayar { get; set; }
        public DbSet<bgk_bildirim> bgk_bildirim { get; set; }
        public DbSet<bgk_butce> bgk_butce { get; set; }
        public DbSet<bgk_dokuman> bgk_dokuman { get; set; }
        public DbSet<bgk_dokuman_kategori> bgk_dokuman_kategori { get; set; }
        public DbSet<bgk_dosya> bgk_dosya { get; set; }
        public DbSet<bgk_etkinlik> bgk_etkinlik { get; set; }
        public DbSet<bgk_etkinlik_gorevli> bgk_etkinlik_gorevli { get; set; }
        public DbSet<bgk_etkinlik_konusmaci> bgk_etkinlik_konusmaci { get; set; }
        public DbSet<bgk_firma> bgk_firma { get; set; }
        public DbSet<bgk_galeri> bgk_galeri { get; set; }
        public DbSet<bgk_galeri_resim> bgk_galeri_resim { get; set; }
        public DbSet<bgk_gorev> bgk_gorev { get; set; }
        public DbSet<bgk_gorev_kategori> bgk_gorev_kategori { get; set; }
        public DbSet<bgk_gorev_kategori_uye> bgk_gorev_kategori_uye { get; set; }
        public DbSet<bgk_gorev_uye> bgk_gorev_uye { get; set; }
        public DbSet<bgk_grup> bgk_grup { get; set; }
        public DbSet<bgk_grup_uye> bgk_grup_uye { get; set; }
        public DbSet<bgk_kategori> bgk_kategori { get; set; }
        public DbSet<bgk_menu> bgk_menu { get; set; }
        public DbSet<bgk_mesaj> bgk_mesaj { get; set; }
        public DbSet<bgk_not> bgk_not { get; set; }
        public DbSet<bgk_oylama> bgk_oylama { get; set; }
        public DbSet<bgk_sayfa> bgk_sayfa { get; set; }
        public DbSet<bgk_seviye> bgk_seviye { get; set; }
        public DbSet<bgk_uye> bgk_uye { get; set; }
        public DbSet<bgk_yazi> bgk_yazi { get; set; }
        public DbSet<bgk_yorum> bgk_yorum { get; set; }
    }
}
