//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.Mobisis.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int Id { get; set; }
        public string StudentId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsSuccessful { get; set; }
        public string ApiUsername { get; set; }
    }
}
