//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKPort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Target { get; set; }
        public bool IsApproval { get; set; }
        public int Sort { get; set; }
        public int PageID { get; set; }
    
        public virtual Page Page { get; set; }
    }
}
