//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKPort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Categories = new HashSet<Category>();
            this.PageWidgets = new HashSet<PageWidget>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ShortURL { get; set; }
        public int PageID { get; set; }
        public int Sort { get; set; }
        public bool IsApproval { get; set; }
        public string SectionTemplate { get; set; }
        public string CategoryTemplate { get; set; }
        public string PostTemplate { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual Page Page { get; set; }
        public virtual ICollection<PageWidget> PageWidgets { get; set; }
    }
}
