//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKPort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Pages = new HashSet<Page>();
            this.Posts = new HashSet<Post>();
            this.Ratings = new HashSet<Rating>();
            this.Subscriptions = new HashSet<Subscription>();
            this.Themes = new HashSet<Theme>();
            this.Widgets = new HashSet<Widget>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ShortURL { get; set; }
        public string ImageURL { get; set; }
        public int Type { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Page> Pages { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
        public virtual ICollection<Theme> Themes { get; set; }
        public virtual ICollection<Widget> Widgets { get; set; }
    }
}
