//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKPort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Widget
    {
        public Widget()
        {
            this.PageWidgets = new HashSet<PageWidget>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int OwnerID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public bool IsApproval { get; set; }
    
        public virtual ICollection<PageWidget> PageWidgets { get; set; }
        public virtual User User { get; set; }
    }
}
