//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerSupport.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Support : ObjectModel
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Subject { get; set; }
        [DataMember]
        public string Content { get; set; }
        [DataMember]
        public System.DateTime SendDate { get; set; }
        [DataMember]
        public bool IsRead { get; set; }
        [DataMember]
        public bool IsFlagged { get; set; }
        [DataMember]
        public int ConsumerId { get; set; }
        [DataMember]
        public int AppId { get; set; }

        [DataMember]
        public virtual App App { get; set; }
        [DataMember]
        public virtual Consumer Consumer { get; set; }
    }
}
