//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Posts = new HashSet<PostCategory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortURL { get; set; }
        public int PostCount { get; set; }
        public bool Approval { get; set; }
    
        public virtual ICollection<PostCategory> Posts { get; set; }
    }
}
