//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Categories = new HashSet<PostCategory>();
            this.Tags = new HashSet<PostTag>();
            this.Ratings = new HashSet<Rating>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string ShortURL { get; set; }
        public int AuthorId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public bool Approval { get; set; }
        public string Summary { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<PostCategory> Categories { get; set; }
        public virtual ICollection<PostTag> Tags { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
