//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_butce
    {
        public int Id { get; set; }
        public string HarcananYer { get; set; }
        public decimal Miktar { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> EtkinlikID { get; set; }
        public Nullable<int> FaturaID { get; set; }
        public int FirmaID { get; set; }
        public Nullable<System.DateTime> IslemTarihi { get; set; }
        public int Islem { get; set; }
    
        public virtual bgk_dosya bgk_dosya { get; set; }
        public virtual bgk_etkinlik bgk_etkinlik { get; set; }
        public virtual bgk_firma bgk_firma { get; set; }
    }
}
