//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_etkinlik_gorevli
    {
        public int Id { get; set; }
        public int UyeID { get; set; }
        public int GorevID { get; set; }
        public int EtkinlikID { get; set; }
    
        public virtual bgk_etkinlik bgk_etkinlik { get; set; }
        public virtual bgk_gorev bgk_gorev { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
    }
}
