//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_yazi
    {
        public bgk_yazi()
        {
            this.bgk_oylama = new HashSet<bgk_oylama>();
            this.bgk_yorum = new HashSet<bgk_yorum>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public string Ozet { get; set; }
        public int KategoriID { get; set; }
        public int UyeID { get; set; }
        public string Seo { get; set; }
        public int Okunma { get; set; }
        public System.DateTime YazimTarihi { get; set; }
        public bool Manset { get; set; }
        public bool Onay { get; set; }
    
        public virtual bgk_kategori bgk_kategori { get; set; }
        public virtual ICollection<bgk_oylama> bgk_oylama { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
        public virtual ICollection<bgk_yorum> bgk_yorum { get; set; }
    }
}
