//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_gorev
    {
        public bgk_gorev()
        {
            this.bgk_etkinlik_gorevli = new HashSet<bgk_etkinlik_gorevli>();
            this.bgk_gorev_uye = new HashSet<bgk_gorev_uye>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> GrupID { get; set; }
        public Nullable<int> KategoriID { get; set; }
        public int OlusturanID { get; set; }
        public int Puan { get; set; }
        public Nullable<int> CezaPuani { get; set; }
        public Nullable<int> GunSayisi { get; set; }
        public System.DateTime OlusturulmaTarihi { get; set; }
        public Nullable<System.DateTime> BitisTarihi { get; set; }
        public int Tip { get; set; }
        public bool Onay { get; set; }
        public Nullable<int> Sira { get; set; }
    
        public virtual ICollection<bgk_etkinlik_gorevli> bgk_etkinlik_gorevli { get; set; }
        public virtual bgk_gorev_kategori bgk_gorev_kategori { get; set; }
        public virtual bgk_grup bgk_grup { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
        public virtual ICollection<bgk_gorev_uye> bgk_gorev_uye { get; set; }
    }
}
