//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_galeri
    {
        public bgk_galeri()
        {
            this.bgk_galeri_resim = new HashSet<bgk_galeri_resim>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public string Seo { get; set; }
        public System.DateTime OlusturulmaTarihi { get; set; }
        public bool Onay { get; set; }
    
        public virtual ICollection<bgk_galeri_resim> bgk_galeri_resim { get; set; }
    }
}
