//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_grup
    {
        public bgk_grup()
        {
            this.bgk_gorev = new HashSet<bgk_gorev>();
            this.bgk_grup_uye = new HashSet<bgk_grup_uye>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public int Tip { get; set; }
    
        public virtual ICollection<bgk_gorev> bgk_gorev { get; set; }
        public virtual ICollection<bgk_grup_uye> bgk_grup_uye { get; set; }
    }
}
