//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_etkinlik_konusmaci
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Konu { get; set; }
        public string Aciklama { get; set; }
        public int EtkinlikID { get; set; }
    
        public virtual bgk_etkinlik bgk_etkinlik { get; set; }
    }
}
