//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bgk_firma
    {
        public bgk_firma()
        {
            this.bgk_butce = new HashSet<bgk_butce>();
            this.bgk_etkinlik = new HashSet<bgk_etkinlik>();
        }
    
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> UyeID { get; set; }
        public int ResimID { get; set; }
    
        public virtual ICollection<bgk_butce> bgk_butce { get; set; }
        public virtual bgk_dosya bgk_dosya { get; set; }
        public virtual ICollection<bgk_etkinlik> bgk_etkinlik { get; set; }
        public virtual bgk_uye bgk_uye { get; set; }
    }
}
