//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class basvuru
    {
        public int Id { get; set; }
        [Display(Name = "Adýnýz")]
        public string Ad { get; set; }
        [Display(Name = "Soyadýnýz")]
        public string Soyad { get; set; }
        [Display(Name = "Kurumunuz")]
        public string Kurum { get; set; }
        [Display(Name = "Mesleðiniz")]
        public string Meslek { get; set; }
        [Display(Name = "Kayýt Tipi")]
        public int Tur { get; set; }
        [Display(Name = "Ödeme Tarihi")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        [Display(Name = "Dekont Numarasý")]
        public string DekontNumarasi { get; set; }
        [Display(Name = "E-posta Adresiniz")]
        public string Email { get; set; }
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Telefon Numaranýz")]
        public int Telefon { get; set; }
        public bool Onay { get; set; }
        [Display(Name = "Þifeniz")]
        public string Sifre { get; set; }
    }
}
