//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class duyuru
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public int Sira { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Onay { get; set; }
        public bool Manset { get; set; }
    }
}
