//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class link
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Adres { get; set; }
        public int Sira { get; set; }
        public bool Onay { get; set; }
        public bool AltLink { get; set; }
        public Nullable<int> UstLinkID { get; set; }
        public bool AnaMenu { get; set; }
    }
}
