//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.Mobisis.Api.ObisisMobileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OgrenciResult", Namespace="http://schemas.datacontract.org/2004/07/ObisisMobileWCF")]
    [System.SerializableAttribute()]
    public partial class OgrenciResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ObisisMobileWCF")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://obisis.erciyes.edu.tr", ConfigurationName="ObisisMobileService.IObisisMobileService")]
    public interface IObisisMobileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciBilgiGetir", ReplyAction="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciBilgiGetirResponse")]
        OK.Mobisis.Api.ObisisMobileService.OgrenciResult OgrenciBilgiGetir(string ogrenciNo, string sifre, System.Nullable<int> ogretimYili, System.Nullable<int> donem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciBilgiGetir", ReplyAction="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciBilgiGetirResponse")]
        System.Threading.Tasks.Task<OK.Mobisis.Api.ObisisMobileService.OgrenciResult> OgrenciBilgiGetirAsync(string ogrenciNo, string sifre, System.Nullable<int> ogretimYili, System.Nullable<int> donem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciDonemGetir", ReplyAction="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciDonemGetirResponse")]
        OK.Mobisis.Api.ObisisMobileService.OgrenciResult OgrenciDonemGetir(string ogrenciNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciDonemGetir", ReplyAction="http://obisis.erciyes.edu.tr/IObisisMobileService/OgrenciDonemGetirResponse")]
        System.Threading.Tasks.Task<OK.Mobisis.Api.ObisisMobileService.OgrenciResult> OgrenciDonemGetirAsync(string ogrenciNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://obisis.erciyes.edu.tr/IObisisMobileService/GetDataUsingDataContract", ReplyAction="http://obisis.erciyes.edu.tr/IObisisMobileService/GetDataUsingDataContractRespons" +
            "e")]
        OK.Mobisis.Api.ObisisMobileService.CompositeType GetDataUsingDataContract(OK.Mobisis.Api.ObisisMobileService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://obisis.erciyes.edu.tr/IObisisMobileService/GetDataUsingDataContract", ReplyAction="http://obisis.erciyes.edu.tr/IObisisMobileService/GetDataUsingDataContractRespons" +
            "e")]
        System.Threading.Tasks.Task<OK.Mobisis.Api.ObisisMobileService.CompositeType> GetDataUsingDataContractAsync(OK.Mobisis.Api.ObisisMobileService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IObisisMobileServiceChannel : OK.Mobisis.Api.ObisisMobileService.IObisisMobileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ObisisMobileServiceClient : System.ServiceModel.ClientBase<OK.Mobisis.Api.ObisisMobileService.IObisisMobileService>, OK.Mobisis.Api.ObisisMobileService.IObisisMobileService {
        
        public ObisisMobileServiceClient() {
        }
        
        public ObisisMobileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ObisisMobileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObisisMobileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ObisisMobileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public OK.Mobisis.Api.ObisisMobileService.OgrenciResult OgrenciBilgiGetir(string ogrenciNo, string sifre, System.Nullable<int> ogretimYili, System.Nullable<int> donem) {
            return base.Channel.OgrenciBilgiGetir(ogrenciNo, sifre, ogretimYili, donem);
        }
        
        public System.Threading.Tasks.Task<OK.Mobisis.Api.ObisisMobileService.OgrenciResult> OgrenciBilgiGetirAsync(string ogrenciNo, string sifre, System.Nullable<int> ogretimYili, System.Nullable<int> donem) {
            return base.Channel.OgrenciBilgiGetirAsync(ogrenciNo, sifre, ogretimYili, donem);
        }
        
        public OK.Mobisis.Api.ObisisMobileService.OgrenciResult OgrenciDonemGetir(string ogrenciNo) {
            return base.Channel.OgrenciDonemGetir(ogrenciNo);
        }
        
        public System.Threading.Tasks.Task<OK.Mobisis.Api.ObisisMobileService.OgrenciResult> OgrenciDonemGetirAsync(string ogrenciNo) {
            return base.Channel.OgrenciDonemGetirAsync(ogrenciNo);
        }
        
        public OK.Mobisis.Api.ObisisMobileService.CompositeType GetDataUsingDataContract(OK.Mobisis.Api.ObisisMobileService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<OK.Mobisis.Api.ObisisMobileService.CompositeType> GetDataUsingDataContractAsync(OK.Mobisis.Api.ObisisMobileService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
