//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTunes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTunes.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to favorites.
        /// </summary>
        public static string AddToFavoritesLabel {
            get {
                return ResourceManager.GetString("AddToFavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string AlbumDetailsTitle {
            get {
                return ResourceManager.GetString("AlbumDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string AlbumLabel {
            get {
                return ResourceManager.GetString("AlbumLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string AlbumSongsTitle {
            get {
                return ResourceManager.GetString("AlbumSongsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iTunes Music.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Count.
        /// </summary>
        public static string ArtistAlbumCountLabel {
            get {
                return ResourceManager.GetString("ArtistAlbumCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string ArtistAlbumsTitle {
            get {
                return ResourceManager.GetString("ArtistAlbumsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string ArtistDetailsTitle {
            get {
                return ResourceManager.GetString("ArtistDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ArtistLabel {
            get {
                return ResourceManager.GetString("ArtistLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Count.
        /// </summary>
        public static string ArtistSongCountLabel {
            get {
                return ResourceManager.GetString("ArtistSongCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string ArtistSongsTitle {
            get {
                return ResourceManager.GetString("ArtistSongsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        public static string ContinueButtonContent {
            get {
                return ResourceManager.GetString("ContinueButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s lonely in here.
        ///You can add song to the favorites list to find later easily..
        /// </summary>
        public static string FavoritesEmptyMessage {
            get {
                return ResourceManager.GetString("FavoritesEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string FavoritesTitle {
            get {
                return ResourceManager.GetString("FavoritesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string GenreLabel {
            get {
                return ResourceManager.GetString("GenreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating albums...
        /// </summary>
        public static string GetAlbumsMessage {
            get {
                return ResourceManager.GetString("GetAlbumsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading songs...
        /// </summary>
        public static string GetAlbumSongsMessage {
            get {
                return ResourceManager.GetString("GetAlbumSongsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading albums...
        /// </summary>
        public static string GetArtistAlbumsMessage {
            get {
                return ResourceManager.GetString("GetArtistAlbumsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading songs...
        /// </summary>
        public static string GetArtistSongsMessage {
            get {
                return ResourceManager.GetString("GetArtistSongsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating songs...
        /// </summary>
        public static string GetSongsMessage {
            get {
                return ResourceManager.GetString("GetSongsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        public static string HomePageLabel {
            get {
                return ResourceManager.GetString("HomePageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in favorites.
        /// </summary>
        public static string InFavoritesLabel {
            get {
                return ResourceManager.GetString("InFavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your data connection..
        /// </summary>
        public static string InternetConnectionError {
            get {
                return ResourceManager.GetString("InternetConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oğuzhan Kiyar.
        /// </summary>
        public static string PublisherName {
            get {
                return ResourceManager.GetString("PublisherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDateLabel {
            get {
                return ResourceManager.GetString("ReleaseDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorites.
        /// </summary>
        public static string RemoveFromFavoritesLabel {
            get {
                return ResourceManager.GetString("RemoveFromFavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchButtonContent {
            get {
                return ResourceManager.GetString("SearchButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching songs...
        /// </summary>
        public static string SearchMessage {
            get {
                return ResourceManager.GetString("SearchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search doesn&apos;t found.
        ///Please try again..
        /// </summary>
        public static string SearchNotFoundMessage {
            get {
                return ResourceManager.GetString("SearchNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string SearchTitle {
            get {
                return ResourceManager.GetString("SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the country for regional list.
        /// </summary>
        public static string SelectCountryLabel {
            get {
                return ResourceManager.GetString("SelectCountryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save settings.
        /// </summary>
        public static string SettingsSaveButtonContent {
            get {
                return ResourceManager.GetString("SettingsSaveButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Count.
        /// </summary>
        public static string SongCountLabel {
            get {
                return ResourceManager.GetString("SongCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string SongDetailsTitle {
            get {
                return ResourceManager.GetString("SongDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song.
        /// </summary>
        public static string SongLabel {
            get {
                return ResourceManager.GetString("SongLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to albums.
        /// </summary>
        public static string TopAlbumsTitle {
            get {
                return ResourceManager.GetString("TopAlbumsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string TopSongsTitle {
            get {
                return ResourceManager.GetString("TopSongsTitle", resourceCulture);
            }
        }
    }
}
