//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Mobisis.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Baglanti", Namespace="http://schemas.datacontract.org/2004/07/ObisisService")]
    public partial class Baglanti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool DurumField;
        
        private string MesajField;
        
        private Mobisis.ServiceReference.Ogrenci OgrenciField;
        
        private string OgrenciNoField;
        
        private string ReferenceField;
        
        private string SifreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((this.DurumField.Equals(value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mesaj {
            get {
                return this.MesajField;
            }
            set {
                if ((object.ReferenceEquals(this.MesajField, value) != true)) {
                    this.MesajField = value;
                    this.RaisePropertyChanged("Mesaj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mobisis.ServiceReference.Ogrenci Ogrenci {
            get {
                return this.OgrenciField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrenciField, value) != true)) {
                    this.OgrenciField = value;
                    this.RaisePropertyChanged("Ogrenci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenciNo {
            get {
                return this.OgrenciNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrenciNoField, value) != true)) {
                    this.OgrenciNoField = value;
                    this.RaisePropertyChanged("OgrenciNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ogrenci", Namespace="http://schemas.datacontract.org/2004/07/ObisisService")]
    public partial class Ogrenci : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdSoyadField;
        
        private string BolumField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.Donem> DonemlerField;
        
        private string FakulteField;
        
        private double GANOField;
        
        private string OgrenciNoField;
        
        private string SifreField;
        
        private int SinifField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdSoyad {
            get {
                return this.AdSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.AdSoyadField, value) != true)) {
                    this.AdSoyadField = value;
                    this.RaisePropertyChanged("AdSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bolum {
            get {
                return this.BolumField;
            }
            set {
                if ((object.ReferenceEquals(this.BolumField, value) != true)) {
                    this.BolumField = value;
                    this.RaisePropertyChanged("Bolum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.Donem> Donemler {
            get {
                return this.DonemlerField;
            }
            set {
                if ((object.ReferenceEquals(this.DonemlerField, value) != true)) {
                    this.DonemlerField = value;
                    this.RaisePropertyChanged("Donemler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fakulte {
            get {
                return this.FakulteField;
            }
            set {
                if ((object.ReferenceEquals(this.FakulteField, value) != true)) {
                    this.FakulteField = value;
                    this.RaisePropertyChanged("Fakulte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GANO {
            get {
                return this.GANOField;
            }
            set {
                if ((this.GANOField.Equals(value) != true)) {
                    this.GANOField = value;
                    this.RaisePropertyChanged("GANO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgrenciNo {
            get {
                return this.OgrenciNoField;
            }
            set {
                if ((object.ReferenceEquals(this.OgrenciNoField, value) != true)) {
                    this.OgrenciNoField = value;
                    this.RaisePropertyChanged("OgrenciNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sinif {
            get {
                return this.SinifField;
            }
            set {
                if ((this.SinifField.Equals(value) != true)) {
                    this.SinifField = value;
                    this.RaisePropertyChanged("Sinif");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Donem", Namespace="http://schemas.datacontract.org/2004/07/ObisisService")]
    public partial class Donem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdiField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.Ders> DerslerField;
        
        private double GANOField;
        
        private int NoField;
        
        private string OgretimYiliField;
        
        private int OgretimYiliKoduField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.Ders> Dersler {
            get {
                return this.DerslerField;
            }
            set {
                if ((object.ReferenceEquals(this.DerslerField, value) != true)) {
                    this.DerslerField = value;
                    this.RaisePropertyChanged("Dersler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double GANO {
            get {
                return this.GANOField;
            }
            set {
                if ((this.GANOField.Equals(value) != true)) {
                    this.GANOField = value;
                    this.RaisePropertyChanged("GANO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int No {
            get {
                return this.NoField;
            }
            set {
                if ((this.NoField.Equals(value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OgretimYili {
            get {
                return this.OgretimYiliField;
            }
            set {
                if ((object.ReferenceEquals(this.OgretimYiliField, value) != true)) {
                    this.OgretimYiliField = value;
                    this.RaisePropertyChanged("OgretimYili");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OgretimYiliKodu {
            get {
                return this.OgretimYiliKoduField;
            }
            set {
                if ((this.OgretimYiliKoduField.Equals(value) != true)) {
                    this.OgretimYiliKoduField = value;
                    this.RaisePropertyChanged("OgretimYiliKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ders", Namespace="http://schemas.datacontract.org/2004/07/ObisisService")]
    public partial class Ders : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AdiField;
        
        private double BasariKatsayisiField;
        
        private System.Nullable<int> ButunlemeField;
        
        private string DurumField;
        
        private System.Nullable<int> FinalField;
        
        private string HarfNotuField;
        
        private string KodField;
        
        private double KrediField;
        
        private System.Nullable<int> OrtalamaField;
        
        private bool OrtalamayaEtkiField;
        
        private int SinifField;
        
        private System.Nullable<int> Vize1Field;
        
        private System.Nullable<int> Vize2Field;
        
        private System.Nullable<int> Vize3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adi {
            get {
                return this.AdiField;
            }
            set {
                if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                    this.AdiField = value;
                    this.RaisePropertyChanged("Adi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BasariKatsayisi {
            get {
                return this.BasariKatsayisiField;
            }
            set {
                if ((this.BasariKatsayisiField.Equals(value) != true)) {
                    this.BasariKatsayisiField = value;
                    this.RaisePropertyChanged("BasariKatsayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Butunleme {
            get {
                return this.ButunlemeField;
            }
            set {
                if ((this.ButunlemeField.Equals(value) != true)) {
                    this.ButunlemeField = value;
                    this.RaisePropertyChanged("Butunleme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Final {
            get {
                return this.FinalField;
            }
            set {
                if ((this.FinalField.Equals(value) != true)) {
                    this.FinalField = value;
                    this.RaisePropertyChanged("Final");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HarfNotu {
            get {
                return this.HarfNotuField;
            }
            set {
                if ((object.ReferenceEquals(this.HarfNotuField, value) != true)) {
                    this.HarfNotuField = value;
                    this.RaisePropertyChanged("HarfNotu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kod {
            get {
                return this.KodField;
            }
            set {
                if ((object.ReferenceEquals(this.KodField, value) != true)) {
                    this.KodField = value;
                    this.RaisePropertyChanged("Kod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Kredi {
            get {
                return this.KrediField;
            }
            set {
                if ((this.KrediField.Equals(value) != true)) {
                    this.KrediField = value;
                    this.RaisePropertyChanged("Kredi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Ortalama {
            get {
                return this.OrtalamaField;
            }
            set {
                if ((this.OrtalamaField.Equals(value) != true)) {
                    this.OrtalamaField = value;
                    this.RaisePropertyChanged("Ortalama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OrtalamayaEtki {
            get {
                return this.OrtalamayaEtkiField;
            }
            set {
                if ((this.OrtalamayaEtkiField.Equals(value) != true)) {
                    this.OrtalamayaEtkiField = value;
                    this.RaisePropertyChanged("OrtalamayaEtki");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sinif {
            get {
                return this.SinifField;
            }
            set {
                if ((this.SinifField.Equals(value) != true)) {
                    this.SinifField = value;
                    this.RaisePropertyChanged("Sinif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vize1 {
            get {
                return this.Vize1Field;
            }
            set {
                if ((this.Vize1Field.Equals(value) != true)) {
                    this.Vize1Field = value;
                    this.RaisePropertyChanged("Vize1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vize2 {
            get {
                return this.Vize2Field;
            }
            set {
                if ((this.Vize2Field.Equals(value) != true)) {
                    this.Vize2Field = value;
                    this.RaisePropertyChanged("Vize2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Vize3 {
            get {
                return this.Vize3Field;
            }
            set {
                if ((this.Vize3Field.Equals(value) != true)) {
                    this.Vize3Field = value;
                    this.RaisePropertyChanged("Vize3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YemekList", Namespace="http://schemas.datacontract.org/2004/07/ObisisService")]
    public partial class YemekList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string OgunField;
        
        private string TarihField;
        
        private System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList.Yemek> YemeklerField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ogun {
            get {
                return this.OgunField;
            }
            set {
                if ((object.ReferenceEquals(this.OgunField, value) != true)) {
                    this.OgunField = value;
                    this.RaisePropertyChanged("Ogun");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((object.ReferenceEquals(this.TarihField, value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList.Yemek> Yemekler {
            get {
                return this.YemeklerField;
            }
            set {
                if ((object.ReferenceEquals(this.YemeklerField, value) != true)) {
                    this.YemeklerField = value;
                    this.RaisePropertyChanged("Yemekler");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="YemekList.Yemek", Namespace="http://schemas.datacontract.org/2004/07/ObisisService")]
        public partial class Yemek : object, System.ComponentModel.INotifyPropertyChanged {
            
            private string AdiField;
            
            private string KaloriField;
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Adi {
                get {
                    return this.AdiField;
                }
                set {
                    if ((object.ReferenceEquals(this.AdiField, value) != true)) {
                        this.AdiField = value;
                        this.RaisePropertyChanged("Adi");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Kalori {
                get {
                    return this.KaloriField;
                }
                set {
                    if ((object.ReferenceEquals(this.KaloriField, value) != true)) {
                        this.KaloriField = value;
                        this.RaisePropertyChanged("Kalori");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.IAsyncResult BeginLogin(string OgrenciNo, string Sifre, string Ref, System.AsyncCallback callback, object asyncState);
        
        Mobisis.ServiceReference.Baglanti EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetFood", ReplyAction="http://tempuri.org/IService1/GetFoodResponse")]
        System.IAsyncResult BeginGetFood(string Ref, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList> EndGetFood(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/CurrentPeriod", ReplyAction="http://tempuri.org/IService1/CurrentPeriodResponse")]
        System.IAsyncResult BeginCurrentPeriod(string OgrenciNo, string Sifre, string Ref, System.AsyncCallback callback, object asyncState);
        
        Mobisis.ServiceReference.Donem EndCurrentPeriod(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Mobisis.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mobisis.ServiceReference.Baglanti Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mobisis.ServiceReference.Baglanti)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFoodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFoodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrentPeriodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CurrentPeriodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mobisis.ServiceReference.Donem Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mobisis.ServiceReference.Donem)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Mobisis.ServiceReference.IService1>, Mobisis.ServiceReference.IService1 {
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetFoodDelegate;
        
        private EndOperationDelegate onEndGetFoodDelegate;
        
        private System.Threading.SendOrPostCallback onGetFoodCompletedDelegate;
        
        private BeginOperationDelegate onBeginCurrentPeriodDelegate;
        
        private EndOperationDelegate onEndCurrentPeriodDelegate;
        
        private System.Threading.SendOrPostCallback onCurrentPeriodCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<GetFoodCompletedEventArgs> GetFoodCompleted;
        
        public event System.EventHandler<CurrentPeriodCompletedEventArgs> CurrentPeriodCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ServiceReference.IService1.BeginLogin(string OgrenciNo, string Sifre, string Ref, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(OgrenciNo, Sifre, Ref, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobisis.ServiceReference.Baglanti Mobisis.ServiceReference.IService1.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string OgrenciNo = ((string)(inValues[0]));
            string Sifre = ((string)(inValues[1]));
            string Ref = ((string)(inValues[2]));
            return ((Mobisis.ServiceReference.IService1)(this)).BeginLogin(OgrenciNo, Sifre, Ref, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            Mobisis.ServiceReference.Baglanti retVal = ((Mobisis.ServiceReference.IService1)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string OgrenciNo, string Sifre, string Ref) {
            this.LoginAsync(OgrenciNo, Sifre, Ref, null);
        }
        
        public void LoginAsync(string OgrenciNo, string Sifre, string Ref, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        OgrenciNo,
                        Sifre,
                        Ref}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ServiceReference.IService1.BeginGetFood(string Ref, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFood(Ref, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList> Mobisis.ServiceReference.IService1.EndGetFood(System.IAsyncResult result) {
            return base.Channel.EndGetFood(result);
        }
        
        private System.IAsyncResult OnBeginGetFood(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Ref = ((string)(inValues[0]));
            return ((Mobisis.ServiceReference.IService1)(this)).BeginGetFood(Ref, callback, asyncState);
        }
        
        private object[] OnEndGetFood(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList> retVal = ((Mobisis.ServiceReference.IService1)(this)).EndGetFood(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFoodCompleted(object state) {
            if ((this.GetFoodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFoodCompleted(this, new GetFoodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFoodAsync(string Ref) {
            this.GetFoodAsync(Ref, null);
        }
        
        public void GetFoodAsync(string Ref, object userState) {
            if ((this.onBeginGetFoodDelegate == null)) {
                this.onBeginGetFoodDelegate = new BeginOperationDelegate(this.OnBeginGetFood);
            }
            if ((this.onEndGetFoodDelegate == null)) {
                this.onEndGetFoodDelegate = new EndOperationDelegate(this.OnEndGetFood);
            }
            if ((this.onGetFoodCompletedDelegate == null)) {
                this.onGetFoodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFoodCompleted);
            }
            base.InvokeAsync(this.onBeginGetFoodDelegate, new object[] {
                        Ref}, this.onEndGetFoodDelegate, this.onGetFoodCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mobisis.ServiceReference.IService1.BeginCurrentPeriod(string OgrenciNo, string Sifre, string Ref, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCurrentPeriod(OgrenciNo, Sifre, Ref, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mobisis.ServiceReference.Donem Mobisis.ServiceReference.IService1.EndCurrentPeriod(System.IAsyncResult result) {
            return base.Channel.EndCurrentPeriod(result);
        }
        
        private System.IAsyncResult OnBeginCurrentPeriod(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string OgrenciNo = ((string)(inValues[0]));
            string Sifre = ((string)(inValues[1]));
            string Ref = ((string)(inValues[2]));
            return ((Mobisis.ServiceReference.IService1)(this)).BeginCurrentPeriod(OgrenciNo, Sifre, Ref, callback, asyncState);
        }
        
        private object[] OnEndCurrentPeriod(System.IAsyncResult result) {
            Mobisis.ServiceReference.Donem retVal = ((Mobisis.ServiceReference.IService1)(this)).EndCurrentPeriod(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCurrentPeriodCompleted(object state) {
            if ((this.CurrentPeriodCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CurrentPeriodCompleted(this, new CurrentPeriodCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CurrentPeriodAsync(string OgrenciNo, string Sifre, string Ref) {
            this.CurrentPeriodAsync(OgrenciNo, Sifre, Ref, null);
        }
        
        public void CurrentPeriodAsync(string OgrenciNo, string Sifre, string Ref, object userState) {
            if ((this.onBeginCurrentPeriodDelegate == null)) {
                this.onBeginCurrentPeriodDelegate = new BeginOperationDelegate(this.OnBeginCurrentPeriod);
            }
            if ((this.onEndCurrentPeriodDelegate == null)) {
                this.onEndCurrentPeriodDelegate = new EndOperationDelegate(this.OnEndCurrentPeriod);
            }
            if ((this.onCurrentPeriodCompletedDelegate == null)) {
                this.onCurrentPeriodCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCurrentPeriodCompleted);
            }
            base.InvokeAsync(this.onBeginCurrentPeriodDelegate, new object[] {
                        OgrenciNo,
                        Sifre,
                        Ref}, this.onEndCurrentPeriodDelegate, this.onCurrentPeriodCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Mobisis.ServiceReference.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Mobisis.ServiceReference.IService1>, Mobisis.ServiceReference.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Mobisis.ServiceReference.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginLogin(string OgrenciNo, string Sifre, string Ref, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = OgrenciNo;
                _args[1] = Sifre;
                _args[2] = Ref;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public Mobisis.ServiceReference.Baglanti EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mobisis.ServiceReference.Baglanti _result = ((Mobisis.ServiceReference.Baglanti)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetFood(string Ref, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Ref;
                System.IAsyncResult _result = base.BeginInvoke("GetFood", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList> EndGetFood(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList> _result = ((System.Collections.ObjectModel.ObservableCollection<Mobisis.ServiceReference.YemekList>)(base.EndInvoke("GetFood", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCurrentPeriod(string OgrenciNo, string Sifre, string Ref, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = OgrenciNo;
                _args[1] = Sifre;
                _args[2] = Ref;
                System.IAsyncResult _result = base.BeginInvoke("CurrentPeriod", _args, callback, asyncState);
                return _result;
            }
            
            public Mobisis.ServiceReference.Donem EndCurrentPeriod(System.IAsyncResult result) {
                object[] _args = new object[0];
                Mobisis.ServiceReference.Donem _result = ((Mobisis.ServiceReference.Donem)(base.EndInvoke("CurrentPeriod", _args, result)));
                return _result;
            }
        }
    }
}
