//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class club_postcomment
    {
        public int Id { get; set; }

        [Display(Name = "Yazan Üye")]
        public Nullable<int> MemberId { get; set; }

        [Display(Name = "Yorum")]
        [Required]
        public string Comment { get; set; }

        [Display(Name = "Yazan Ziyaretçi")]
        public string WriterName { get; set; }

        [Display(Name = "Yazý")]
        public Nullable<int> PostId { get; set; }

        [Display(Name = "Yazýlma Tarihi")]
        public Nullable<System.DateTime> WritingDate { get; set; }

        [Display(Name = "Onay Durumu")]
        public Nullable<bool> IsApproval { get; set; }
    
        public virtual club_member club_member { get; set; }
        public virtual club_post club_post { get; set; }
    }
}
