//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class club_member
    {
        public club_member()
        {
            this.club_groups = new HashSet<club_groupmember>();
            this.club_comments = new HashSet<club_postcomment>();
            this.club_posts = new HashSet<club_post>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Okul Numarasý")]
        public Nullable<int> SchoolNo { get; set; }

        [Display(Name = "Üye Adý")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Email")]
        [Required]
        public string Email { get; set; }

        [Display(Name = "Þifre")]
        [DataType(DataType.Password)]
        [Required]
        public string Password { get; set; }

        [Display(Name = "Resim Adresi")]
        public string Image { get; set; }

        [Display(Name = "Fakülte")]
        public string Faculty { get; set; }

        [Display(Name = "Bölüm")]
        public string Program { get; set; }

        [Display(Name = "Sýnýf")]
        public string Class { get; set; }

        [Display(Name = "Doðum Tarihi")]
        public Nullable<System.DateTime> Birthday { get; set; }

        [Display(Name = "Cinsiyet")]
        public string Gender { get; set; }

        [Display(Name = "Hakkýnda")]
        [AllowHtml]
        public string About { get; set; }

        [Display(Name = "Kayýt Tarihi")]
        public Nullable<System.DateTime> RegistrationDate { get; set; }

        [Display(Name = "Yetki")]
        public Nullable<int> Role { get; set; }

        [Display(Name = "Onay Durumu")]
        public Nullable<bool> IsApproval { get; set; }
    
        public virtual ICollection<club_groupmember> club_groups { get; set; }
        public virtual ICollection<club_postcomment> club_comments { get; set; }
        public virtual ICollection<club_post> club_posts { get; set; }
    }
}
