//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class club_post
    {
        public club_post()
        {
            this.club_comments = new HashSet<club_postcomment>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Baþlýk")]
        [Required(ErrorMessage = "Baþlýk alanýný boþ býraktýnýz.")]
        public string Title { get; set; }

        [Display(Name = "Ýçerik")]
        [AllowHtml]
        [Required(ErrorMessage = "Ýçerik alanýný boþ býraktýnýz.")]
        public string Content { get; set; }

        [Display(Name = "Resim Adresi")]
        public string Image { get; set; }

        [Display(Name = "Yazan")]
        public Nullable<int> MemberId { get; set; }

        [Display(Name = "Kategori")]
        [Required(ErrorMessage = "Kategori alanýný boþ býraktýnýz.")]
        public Nullable<int> CategoryId { get; set; }

        [Display(Name = "Grup")]
        public Nullable<int> GroupId { get; set; }

        [Display(Name = "Yazýlma Tarihi")]
        public Nullable<System.DateTime> WritingDate { get; set; }

        [Display(Name = "Deðiþtirilme Tarihi")]
        public Nullable<System.DateTime> ModifyDate { get; set; }

        [Display(Name = "Okunma Sayýsý")]
        public Nullable<int> ViewsCount { get; set; }
        public string Seo { get; set; }

        [Display(Name = "Onay Durumu")]
        public Nullable<bool> IsApproval { get; set; }
    
        public virtual club_category club_category { get; set; }
        public virtual club_group club_group { get; set; }
        public virtual club_member club_member { get; set; }
        public virtual ICollection<club_postcomment> club_comments { get; set; }
    }
}
