//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class club_group
    {
        public club_group()
        {
            this.club_members = new HashSet<club_groupmember>();
            this.club_posts = new HashSet<club_post>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Grup Adý")]
        [Required]
        public string Name { get; set; }

        [Display(Name = "Grup Açýklamasý")]
        [AllowHtml]
        public string Description { get; set; }

        [Display(Name = "Alt Grup Mu?")]
        public Nullable<bool> IsSubGroup { get; set; }

        [Display(Name = "Üst Grup")]
        public Nullable<int> ParentGroupId { get; set; }
        public string Seo { get; set; }

        [Display(Name = "Sýra")]
        public Nullable<int> Sort { get; set; }
    
        public virtual ICollection<club_groupmember> club_members { get; set; }
        public virtual ICollection<club_post> club_posts { get; set; }
    }
}
