//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class club_notice
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Baþlýk")]
        public string Title { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Duyuru")]
        public string Content { get; set; }

        [Required]
        [Display(Name = "Resim Adresi")]
        public string Image { get; set; }

        [Display(Name = "Yazýlma Tarihi")]
        public Nullable<System.DateTime> WritingDate { get; set; }
        public string Seo { get; set; }

        [Display(Name = "Sýra")]
        public Nullable<int> Sort { get; set; }

        [Display(Name = "Onay Durumu")]
        public Nullable<bool> IsApproval { get; set; }
    }
}
