//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class club_config
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Anahtar Sözcük")]
        public string Key { get; set; }

        [Required]
        [AllowHtml]
        [Display(Name = "Deðer")]
        public string Value { get; set; }

        [Required]
        [Display(Name = "Açýklama")]
        public string Description { get; set; }
    }
}
