//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKComplex.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OKDbEntities : DbContext
    {
        public OKDbEntities()
            : base("name=OKDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<category> category { get; set; }
        public DbSet<comment> comment { get; set; }
        public DbSet<config> config { get; set; }
        public DbSet<forum> forum { get; set; }
        public DbSet<menulink> menulink { get; set; }
        public DbSet<message> message { get; set; }
        public DbSet<notice> notice { get; set; }
        public DbSet<post> post { get; set; }
        public DbSet<rating> rating { get; set; }
        public DbSet<topic> topic { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<usertype> usertype { get; set; }
    }
}
