//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.CargoTracking.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CargoTrackingEntities : DbContext
    {
        public CargoTrackingEntities()
            : base("name=CargoTrackingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Button> Buttons { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<DeviceMessage> DeviceMessages { get; set; }
        public virtual DbSet<Factory> Factories { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<MessageButton> MessageButtons { get; set; }
    }
}
