//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OK.CargoTracking.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceMessage
    {
        public int Id { get; set; }
        public int DeviceId { get; set; }
        public int MessageId { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentAt { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Message Message { get; set; }
    }
}
