//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKFortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class category
    {
        public category()
        {
            this.forums = new HashSet<forum>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Kategori Adý")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Kategori Açýklamasý")]
        public string Description { get; set; }

        public string Seo { get; set; }

        [Display(Name = "Sýra")]
        public Nullable<int> Sort { get; set; }

        [Display(Name = "Onay")]
        public Nullable<bool> IsApproval { get; set; }
    
        public virtual ICollection<forum> forums { get; set; }
    }
}
