//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKFortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class comment
    {
        public comment()
        {
            this.topic1 = new HashSet<topic>();
        }

        public int Id { get; set; }

        [AllowHtml]
        [Required(ErrorMessage = "Cevabýnýz en az 10 karakter olmalý..")]
        //[RegularExpression(@"^.{10,}$", ErrorMessage = "Cevabýnýz en az 10 karakter olmalý.. Tekrar deneyin..")]
        [Display(Name = "Cevap: ", Description = "En az 10 karakterden oluþan birþeyler yazýn..")]
        public string Content { get; set; }

        public Nullable<int> TopicId { get; set; }
        public Nullable<int> WriterId { get; set; }
        public string Rating { get; set; }
        public string QuoteId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsApproval { get; set; }

        [Display(Name = "Düzenlenme Tarihi Deðiþtirilsin mi?")]
        public bool ChangeModifyDate { get; set; }
    
        public virtual topic topic { get; set; }
        public virtual user user { get; set; }
        public virtual ICollection<topic> topic1 { get; set; }
    }
}
