//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKFortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class config
    {
        public int Id { get; set; }
        public string Key { get; set; }
        [AllowHtml]
        public string Value { get; set; }
        public string Description { get; set; }
    }
}
