//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKFortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class notice
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        [DisplayFormat(DataFormatString = "{0:d MMMMMMM yyyy}")]
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsApproval { get; set; }
    }
}
