//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OKFortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class user
    {
        public user()
        {
            this.comments = new HashSet<comment>();
            this.posts = new HashSet<post>();
            this.ratings = new HashSet<rating>();
            this.topics = new HashSet<topic>();
        }

        [Display(Name = "Beni biraz böyle hatýrla :)")]
        public bool RememberMe { get; set; }

        public int Id { get; set; }

        [Display(Name = "Kullanýcý Adý: ", Description = "Kullanýcý adýný deðiþtiremezsin..")]
        public string UserName { get; set; }

        [Display(Name = "Þifre: ", Description = "Deðiþtirmek için alttaki düðmeye týklayýn..")]
        public string Password { get; set; }

        [Display(Name = "Þifre Tekrar")]
        public string ConfirmPassword { get; set; }

        [Display(Name = "Þuanki Þifre: ", Description = "Þuan geçerli olan þifrenizi giriniz..")]
        public string OldPassword { get; set; }

        [Display(Name = "Yeni Þifre")]
        public string NewPassword { get; set; }

        [Display(Name = "Þifre Tekrar")]
        public string ConfirmNewPassword { get; set; }

        [Display(Name = "Ýsim")]
        public string Name { get; set; }

        public string Email { get; set; }

        [Display(Name = "Profil Resmi ", Description = "Ýster bir resim adresi gir, ister bilgisayardan yükle..")]
        public string ImageFile { get; set; }

        [Display(Name = "Profil Resmi: ", Description = "Bir resim seçin..")]
        public string ImageUpload { get; set; }

        [Display(Name = "Cinsiyet")]
        public string Gender { get; set; }

        [Display(Name = "Meslek")]
        public string Job { get; set; }

        [Display(Name = "Yaþýn ", Description = "Doðum tarihini gir..")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:d MMMMMMM yyyy}")]
        public Nullable<System.DateTime> Birthday { get; set; }

        [Display(Name = "Yaþadýðýn Þehir")]
        public string City { get; set; }

        [Display(Name = "Sosyal Site Adreslerin ", Description = "Üyelerin sana ulaþabilecekleri sosyal profil adreslerini yaz..")]
        public string SocialSites { get; set; }

        [Display(Name = "Hakkýnda ", Description = "Kendini tanýt biraz..")]
        public string About { get; set; }

        [Display(Name = "Kayýt Tarihi")]
        [DisplayFormat(DataFormatString = "{0:d MMMMMMM yyyy}")]
        public Nullable<System.DateTime> RegistrationDate { get; set; }

        [Display(Name = "Son Giriþ")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:d MMMMMMM yyyy}")]
        public Nullable<System.DateTime> LastLoginDate { get; set; }

        [Display(Name = "Giriþ Sayýsý")]
        public Nullable<int> LoginCount { get; set; }

        public Nullable<int> Rating { get; set; }
        public Nullable<int> TypeId { get; set; }

        [Display(Name = "Görünen Ýsim ", Description = "Yaptýðýn iþlemlerde görünecek isimini seç..")]
        public Nullable<int> DisplayType { get; set; }

        [Display(Name = "Yasak Durumu")]
        public Nullable<bool> IsBanned { get; set; }

        [Display(Name = "Onay Durumu")]
        public Nullable<bool> IsApproval { get; set; }

        [Display(Name = "Onay Kodu")]
        public string ConfirmationCode { get; set; }
    
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
        public virtual ICollection<topic> topics { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual usertype type { get; set; }
    }
    public class LoginModel
    {
        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Kullanýcý Adý")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [DataType(DataType.Password)]
        [Display(Name = "Þifre")]
        public string Password { get; set; }

        [Display(Name = "Beni biraz böyle hatýrla :)")]
        public bool RememberMe { get; set; }
    }
    public class ChangePasswordModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [DataType(DataType.Password)]
        [Display(Name = "Þuanki Þifre: ", Description = "Þuan geçerli olan þifrenizi giriniz..")]
        public string OldPassword { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [DataType(DataType.Password)]
        [Display(Name = "Yeni Þifre")]
        public string NewPassword { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "Þifreler uyuþmuyor")]
        [Display(Name = "Þifre Tekrar")]
        public string ConfirmNewPassword { get; set; }
    }
    public class MyPasswordModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Kullanýcý Adý")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [RegularExpression(@"^(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}$", ErrorMessage = "Geçersiz email adresi")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Yeni Þifre")]
        [DataType("password")]
        public string NewPassword { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Compare("NewPassword", ErrorMessage = "Þifreler uyuþmuyor")]
        [Display(Name = "Þifre Tekrar")]
        [DataType("password")]
        public string ConfirmNewPassword { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Onay Kodu")]
        public string ConfirmationCode { get; set; }
    }
    public class RegisterModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Kullanýcý Adý")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [StringLength(100, ErrorMessage = "{0} en az {2} karakter olmalýdýr", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Þifre")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Þifre Tekrar")]
        [Compare("Password", ErrorMessage = "Þifreler uyuþmuyor")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [RegularExpression(@"^(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6}$", ErrorMessage = "Geçersiz email adresi")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Ýsim")]
        public string Name { get; set; }

        [Display(Name = "Profil Resmi")]
        public string ImageFile { get; set; }

        [Required(ErrorMessage = "Boþ geçilemez")]
        [Display(Name = "Onay Kodu")]
        public string ConfirmationCode { get; set; }
    }
}
